app = "cyphus-ttrss"
kill_signal = "SIGINT"
kill_timeout = 30
processes = []

[env]
  TTRSS_SELF_URL_PATH = "https://cyphus-ttrss.fly.dev/tt-rss"

[mounts]
  source = "data"
  destination = "/var/www/html"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 80
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "2m"
    interval = "15s"
    restart_limit = 0
    timeout = "5s"
